Updating

diff --git a/atom/atom.SlackBuild b/atom/atom.SlackBuild
--- a/atom/atom.SlackBuild
+++ b/atom/atom.SlackBuild
@@ -59,9 +59,6 @@ cd $PKGNAM-$VERSION
 chown -R root:root .
 chmod -R u+w,go+r-w,a+X-s .
 
-# Disable send metrics to Google Analytics module
-sed -e '/"metrics":/d' -e '/"exception-reporting":/d' -i package.json
-
 # Apply patches
 if [ -e $CWD/patches ]; then
   for PATCH in $CWD/patches/*.patch; do
@@ -69,13 +66,16 @@ if [ -e $CWD/patches ]; then
   done
 fi
 
+sed -i -e 's@node script/bootstrap@node script/bootstrap --no-quiet@g' \
+./script/build || die "Fail fixing verbosity of script/build"
+
 sed -i -e "/-ui/d" \
        -e "/-theme/d" \
        -e "/-syntax/d" \
        -e "/exception-reporting/d" \
        -e "/metrics/d" \
-       -e "s/\"language-gfm\": \".*\",/\"language-gfm2\": \"0.90.4\",\n    \"language-liquid\": \"0.5.1\",\n    \"language-ini-desktop\": \"1.18.2\",\n    \"language-patch2\": \"0.1.3\",\n    \"dark-bint-syntax\": \"0.8.9\",\n    \"fusion-ui\": \"0.10.8\",/g" \
-       -e "s/\"language-shellscript\": \".*\",/\"language-unix-shell\": \"0.33.0\",/g" \
+       -e "s/\"language-gfm\": \".*\",/\"language-gfm2\": \"0.92.1\",\n    \"language-liquid\": \"0.5.1\",\n    \"language-ini-desktop\": \"1.18.3\",\n    \"language-patch2\": \"0.2.0\",\n    \"dark-bint-syntax\": \"0.8.9\",\n    \"fusion-ui\": \"0.11.1\",/g" \
+       -e "s/\"language-shellscript\": \".*\",/\"language-unix-shell\": \"0.37.0\",\n    \"terminal-fusion\": \"2.2.3\",/g" \
        -e "/\"dependencies\": {/a \
             \"language-patch2\": \"fusion809/language-patch2\"," package.json
 
